### PR TITLE
Several fixes for recent issues around Azure provisioning

### LINKED ISSUE #432: [bug] fail to create windows instance
I am using following command which fails to create windows instance 
```
podman run --rm --name create-windows-dektop -d \
    -v ${PWD}:/workspace:z \
    -e ARM_TENANT_ID=${ARM_TENANT_ID} \
    -e ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID} \
    -e ARM_CLIENT_ID=${ARM_CLIENT_ID} \
    -e ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET} \
    quay.io/redhat-developer/mapt:v0.8.0 azure windows create \
        --project-name "praveen-local" \
        --backed-url "file:///workspace" \
        --conn-details-output "/workspace" \
        --windows-version '11' \
        --windows-featurepack '23h2-ent' \
```

podman logs 
```
[...]
64as_cc_v5,Standard_EC96as_cc_v5,Standard_EC4ads_cc_v5,Standard_EC8ads_cc_v5,Standard_EC16ads_cc_v5,Standard_EC20ads_cc_v5,Standard_EC32ads_cc_v5,Standard_EC48ads_cc_v5,Standard_EC64ads_cc_v5,Standard_EC96ads_cc_v5,Standard_L8s_v3,Standard_L16s_v3,Standard_L32s_v3,Standard_L48s_v3,Standard_L64s_v3,Standard_L80s_v3,Standard_NC6s_v3,Standard_NC12s_v3,Standard_NC24rs_v3,Standard_NC24s_v3,Standard_M64,Standard_M64m,Standard_M128,Standard_M128m,Standard_M8-2ms,Standard_M8-4ms,Standard_M8ms,Standard_M16-4ms,Standard_M16-8ms,Standard_M16ms,Standard_M32-8ms,Standard_M32-16ms,Standard_M32ls,Standard_M32ms,Standard_M32ts,Standard_M64-16ms,Standard_M64-32ms,Standard_M64ls,Standard_M64ms,Standard_M64s,Standard_M128-32ms,Standard_M128-64ms,Standard_M128ms,Standard_M128s,Standard_M32ms_v2,Standard_M64ms_v2,Standard_M64s_v2,Standard_M128ms_v2,Standard_M128s_v2,Standard_M192ims_v2,Standard_M192is_v2,Standard_M32dms_v2,Standard_M64dms_v2,Standard_M64ds_v2,Standard_M128dms_v2,Standard_M128ds_v2,Standard_M192idms_v2,Standard_M192ids_v2,Standard_M12s_v3,Standard_M24s_v3,Standard_M48s_1_v3,Standard_M96s_1_v3,Standard_M96s_2_v3,Standard_M176s_3_v3,Standard_M176s_4_v3,Standard_M12ds_v3,Standard_M24ds_v3,Standard_M48ds_1_v3,Standard_M96ds_1_v3,Standard_M96ds_2_v3,Standard_M176ds_3_v3,Standard_M176ds_4_v3,Standard_E96ias_v4,Standard_M208ms_v2,Standard_M208s_v2,Standard_M416-208s_v2,Standard_M416s_v2,Standard_M416-208ms_v2,Standard_M416ms_v2,Standard_M416s_8_v2,Standard_M416s_9_v2,Standard_M416s_10_v2,Standard_D2plds_v5,Standard_D4plds_v5,Standard_D8plds_v5,Standard_D16plds_v5,Standard_D32plds_v5,Standard_D48plds_v5,Standard_D64plds_v5,Standard_D2pls_v5,Standard_D4pls_v5,Standard_D8pls_v5,Standard_D16pls_v5,Standard_D32pls_v5,Standard_D48pls_v5,Standard_D64pls_v5,Standard_D2pds_v5,Standard_D4pds_v5,Standard_D8pds_v5,Standard_D16pds_v5,Standard_D32pds_v5,Standard_D48pds_v5,Standard_D64pds_v5,Standard_D2ps_v5,Standard_D4ps_v5,Standard_D8ps_v5,Standard_D16ps_v5,Standard_D32ps_v5,Standard_D48ps_v5,Standard_D64ps_v5,Standard_E2pds_v5,Standard_E4pds_v5,Standard_E8pds_v5,Standard_E16pds_v5,Standard_E20pds_v5,Standard_E32pds_v5,Standard_E2ps_v5,Standard_E4ps_v5,Standard_E8ps_v5,Standard_E16ps_v5,Standard_E20ps_v5,Standard_E32ps_v5,Standard_B2pls_v2,Standard_B2ps_v2,Standard_B2pts_v2,Standard_B4pls_v2,Standard_B4ps_v2,Standard_B8pls_v2,Standard_B8ps_v2,Standard_B16pls_v2,Standard_B16ps_v2,Standard_NV6ads_A10_v5,Standard_NV12ads_A10_v5,Standard_NV18ads_A10_v5,Standard_NV36adms_A10_v5,Standard_NV36ads_A10_v5,Standard_NV72ads_A10_v5. Find out more on the valid VM sizes in each region at https://aka.ms/azure-regionservices." 
INFO                                              
INFO Outputs:                                     
INFO     praveen-local-awdAdminUserPassword: [secret] 
INFO     praveen-local-awdAdminUsername    : "rhqpadmin" 
INFO     praveen-local-awdHost             : "13.94.45.120" 
INFO     praveen-local-awdUserPassword     : [secret] 
INFO     praveen-local-awdUserPrivatekey   : [secret] 
INFO     praveen-local-awdUsername         : "rhqp" 
INFO                                              
INFO Resources:                                   
INFO     + 10 created                             
INFO                                              
INFO Duration: 31s                                
INFO                                              
ERRO failed to run update: exit status 255
code: 255
stdout: Updating (stackCreateWindowsDesktop-praveen-local):

```

### LINKED ISSUE #433: [bug] Problems to pick up small VM flavors with existing subscriptions
I am trying to run some smaller size-VMs, here the command:
```
        # Create instance
        podman run -d --name windows-create --rm \
          -v ${PWD}:/workspace:z \
          -e ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }} \
          -e ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }} \
          -e ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }} \
          -e ARM_CLIENT_SECRET='${{ secrets.ARM_CLIENT_SECRET }}' \
          ${{ env.MAPT_IMAGE }}:${{ env.MAPT_VERSION }} azure \
            windows create \
            --project-name 'windows-desktop' \
            --backed-url 'file:///workspace' \
            --conn-details-output '/workspace' \
            --windows-version '${{ matrix.windows-version }}' \
            --windows-featurepack '${{ matrix.windows-featurepack }}' \
            --nested-virt \
            --cpus 4 \
            --memory 8 \
            --tags project=podman-desktop,source=github,org=${{github.repository_owner}},run=https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \
            --spot
        # Check logs 
        podman logs -f windows-create
```

And I got:
```
INFO azure-native:compute:VirtualMachine (windows-desktop-awd-vm):
INFO error: Status=400 Code="InvalidParameter" Message="The requested VM size standard_d4ads_v6 is not available to the current subscription. To access the requested VM Size, subscription must have one of the following feature flags registered : Microsoft.Compute/DaEaV6Series,Microsoft.Compute/TestSubscription,Microsoft.Compute/VMSKUPreview. The sizes available to the current subscription are: Standard_D2plds_v5,Standard_D4plds_v5,Standard_D8plds_v5,Standard_D16plds_v5,Standard_D32plds_v5 ...
```

### LINKED ISSUE #434: [bug] regression on refactor gh selfhosted runner code
As https://github.com/redhat-developer/mapt/blob/eaf24bec441c3f8751e1e2b436730b005bf29703/pkg/integrations/integrations.go#L25 is using an interface it always is != nil ...so the no snippet is never returned...

Right now every target without cicd integration params will fail

### PR DESCRIPTION
**Pull request by adrianriobo**
Fix #432
Fix #433
Fix #434

Signed-off-by: Adrian Riobo <ariobolo@redhat.com>

### CODE REVIEW

File: pkg/provider/azure/data/vmsize.go [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+)
+
+func IsVMSizeOfferedByLocation(vmSize, location string) (bool, error) {
+	offerings, err := FilterVMSizeOfferedByLocation([]string{vmSize}, location)
+	return len(offerings) == 1, err
+}
+
+// Get InstanceTypes offerings on current location
+func FilterVMSizeOfferedByLocation(vmSizes []string, location string) ([]string, error) {
+	// Create a new Azure credential (uses environment variables or managed identity)
```
Comment (anjannath) [inline pkg/provider/azure/data/vmsize.go:20]: might be needed to use this here to convert the pulumi env variables starting with `AZURE_` to ones starting with `ARM_` since the azure sdk expects it to start with `ARM_` 

https://github.com/redhat-developer/mapt/blob/eaf24bec441c3f8751e1e2b436730b005bf29703/pkg/provider/azure/module/identity/azidentity.go#L19

File: pkg/integrations/integrations.go [hunk 2]
```diff
@@ -23,11 +23,11 @@ type IntegrationConfig interface {
 }
 
 func GetIntegrationSnippet(intCfg IntegrationConfig, username string) (*string, error) {
-	if intCfg == nil {
+	userDatatValues := intCfg.GetUserDataValues()
```
Comment (anjannath) [inline pkg/integrations/integrations.go:26]: will it break if `intCfg` is nil, i am not sure if we can call this method `intCfg.GetUserDataValues()` when `intCfg` is nil

Comment (adrianriobo) [reply pkg/integrations/integrations.go:26]: This do not break, cause it is an interface, and interface always != nil, even when the content inside is nil (mean the struct which should implement the interface) this was the main issue around this. Probably we can refactor a bit better allowing only 1 integration per execution. 

But at least this does not break...as currently main is breaking

Comment (anjannath) [reply pkg/integrations/integrations.go:26]: nvm, i think its fine, since we always create a var in the package, it never nil

Comment (anjannath) [reply pkg/integrations/integrations.go:26]: > Probably we can refactor a bit better allowing only 1 integration per execution.

i was thinking to enforce this at the flag/cmd level.. preventing to pass both github and cirrus integration flags together.. add a validation to check only one integration flags are passed

Comment (adrianriobo) [reply pkg/integrations/integrations.go:26]: Yeah well we can do couple of things....

at logic level (pkg integrations... just return 1 integration snippet) 
at cmd level we can only allow flags for one or we can crate a common set flags (i.e. --integration-target (gh / cirrus), --integration-token, --integration-repo (if required in case you are using gh as target)
with this approach you already ensures only one integration can be set

File: pkg/integrations/integrations.go [hunk 3]
```diff
@@ -23,11 +23,11 @@ type IntegrationConfig interface {
...
+	if userDatatValues == nil {
```
Comment (anjannath) [inline pkg/integrations/integrations.go:27]: small typo here `s/userDatatValues/userDataValues`

Comment (adrianriobo) [reply pkg/integrations/integrations.go]: Fixed

**Review by anjannath — APPROVED** [review]
LGTM
