### PR TITLE
feat(eks): enhancements and fixes for EKS

### LINKED ISSUE #499: EKS Enhancements
This is a following for https://github.com/redhat-developer/mapt/issues/357

- [ ] Add tekton task
- [ ] Check https://www.pulumi.com/docs/iac/clouds/aws/guides/eks/#configuring-your-eks-clusters-worker-nodes-and-node-groups it includes a max spot price attribute. Currently is working but price seems a bit higher..not sure how is managed
- [ ] Extend documentation
- [ ] Add ForceDestroy on destroy operation

### PR DESCRIPTION
**Pull request by zdrapela**
### Self-managed node groups with spot support
- Replace EKS managed node group with a self-managed Auto Scaling Group (ASG) for direct spot price control
- Add `spotPrice` parameter to set maximum bid for spot instances
- Use API authentication mode with access entries for self-managed node authentication

### Cluster reliability fixes
- Add service CIDR to nodeadm `NodeConfig` (required by AL2023 for proper pod networking without `DescribeCluster` API calls)
- Deploy addons in phased dependency order: infrastructure addons (vpc-cni, kube-proxy, eks-pod-identity-agent) → coredns → remaining addons (aws-ebs-csi-driver)
- Add `WaitForCapacityTimeout`, `HealthCheckType`, and `HealthCheckGracePeriod` to ASG so Pulumi waits for nodes to be InService before deploying addons
- Add `ResolveConflictsOnCreate` and extended timeouts to all EKS addons
- Make LB controller depend on coredns for DNS resolution
- Remove unused NAT gateway (`NatGatewayModeNone`) since EKS uses only public subnets

### VPC endpoint extraction
- Extract VPC endpoint creation from per-subnet code into a shared `EndpointsRequest` module
- Endpoints are created once per VPC across all public subnets (required for multi-AZ EKS — AWS allows only one S3 gateway endpoint per VPC)
- Integrates with the opt-in `ServiceEndpoints` pattern from #754

### Other
- Remove AWS CLI dependency from EKS cluster creation
- Add resource tags to all EKS-specific AWS resources (cluster, IAM roles, OIDC provider, addons, ASG, etc.)
- Extend EKS documentation

Resolves #499

### CODE REVIEW

**Comment by zdrapela** [comment]
@adrianriobo Hi, I tested this PR on creating an EKS cluster, but I haven't tested any other infra creation, which may be affected. 
If this PR is too big, I can split it. 
~~I would create a Tekton task, but unfortunately, I don't have a place to test it.~~ I created the Tekton task, but I still don't have where to test it.

**Comment by adrianriobo** [comment]
hey nice contribution, yeah I think most of the changes should not affect other targets but I want to give a try, in any case can you clean a bit the commits? basically you can either group EKS improvements and Networking improvements? WDYT?

**Comment by zdrapela** [comment]
Sure, I split it 👍

**Comment by adrianriobo** [comment]
@anjannath would you find time to review this one?

File: pkg/provider/aws/action/eks/eks.go [hunk 1]
```diff
@@ -159,7 +160,7 @@ func (r *eksRequest) deployer(ctx *pulumi.Context) error {
 		AvailabilityZones:  r.availabilityZones,
 		PublicSubnetsCIDRs: network.GeneratePublicSubnetCIDRs(len(r.availabilityZones)),
 		Region:             *r.allocationData.Region,
-		NatGatewayMode:     &network.NatGatewayModeSingle,
+		NatGatewayMode:     &network.NatGatewayModeNone,
```
Comment (anjannath) [inline pkg/provider/aws/action/eks/eks.go:166]: this seems like can be put into its separate commit, it is changed to `NatGatewayModeNone` because `MapPublicIp` is true and that means a NAT gateway is not needed, we can include that information in the commit log

File: pkg/provider/aws/action/eks/nodegroup.go [hunk 2]
```diff
@@ -0,0 +1,248 @@
...
+	tags              pulumi.StringMap
+}
+
+// createSelfManagedNodeGroup creates an ASG-based self-managed EKS node group.
+// For spot mode (spotPrice != nil), it sets SpotMaxPrice on the ASG mixed instances policy.
+// For on-demand mode, it uses 100% on-demand capacity.
+func createSelfManagedNodeGroup(ctx *pulumi.Context, args *selfManagedNodeGroupArgs) (*autoscaling.Group, error) {
+	// Look up EKS-optimized AL2023 AMI
+	eksAMI, err := ami.GetAMIByName(ctx,
+		fmt.Sprintf("amazon-eks-node-al2023-x86_64-standard-%s-*", args.kubernetesVersion),
```
Comment (anjannath) [inline pkg/provider/aws/action/eks/nodegroup.go]: the eks command also supports the `--arch` flag, here we need to set the `arch` substring in the AMI name, now it is static to `x86_64`

**Comment by zdrapela** [comment]
Thank you @anjannath, good points. I addressed your review comments.

**Comment by adrianriobo** [comment]
Hey we added a new release process for mapt offering now the binary too, I will wait for this PR to goes in and I release `v0.13.0`

so if you have a moment and changes are good @anjannath LGTM and we can merge

**Comment by anjannath** [comment]
@zdrapela @adrianriobo seeing an error when trying to deploye `arm64` cluster:

```
Diagnostics:
  pulumi:pulumi:Stack (anath-mapt-eks-stackCreateEKS-anath-mapt-eks):
    error: update failed

  aws:autoscaling:Group (main-aeks-asg):
    error:   sdk-v2/provider2.go:572: sdk.helper_schema: creating Auto Scaling Group (main-aeks-asg-d8e26a7): operation error Auto Scaling: CreateAutoScalingGroup, https response error StatusCode: 400, RequestID: 5c723822-46a0-4004-a933-e6225b9f7f66, api error ValidationError: You must use a valid fully-formed launch template. The architecture 'x86_64' of the specified instance type does not match the architecture 'arm64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI.: provider=aws@7.25.0
    error: 1 error occurred:
    	* creating Auto Scaling Group (main-aeks-asg-d8e26a7): operation error Auto Scaling: CreateAutoScalingGroup, https response error StatusCode: 400, RequestID: 5c723822-46a0-4004-a933-e6225b9f7f66, api error ValidationError: You must use a valid fully-formed launch template. The architecture 'x86_64' of the specified instance type does not match the architecture 'arm64' of the specified AMI. Specify an instance type and an AMI that have matching architectures, and try again. You can use 'describe-instance-types' or 'describe-images' to discover the architecture of the instance type or AMI.
```

**Comment by adrianriobo** [comment]
@zdrapela how did you try it, either you set `--compute-size` so you need to ensure types in the list are arm64 or either `--arch`  allowing mapt pick the instance for you

**Comment by adrianriobo** [comment]
@zdrapela do you recall the inputs for the test? so I can try to replicate it?

**Comment by zdrapela** [comment]
Hi, I've used these exact args while testing it:
```
 "aws", "eks", "create",
        "--debug-level", "9",
        "--project-name", "debug-eks",
        "--backed-url", "s3://xxx",
        "--conn-details-output", "xxx",
        "--version", "1.34",
        "--workers-max", "3",
        "--workers-desired", "3",
        "--cpus", "2",
        "--memory", "4",
        "--arch", "arm64",
        "--spot",
        "--addons", "aws-ebs-csi-driver,coredns,eks-pod-identity-agent,kube-proxy,vpc-cni",
        "--load-balancer-controller",
        "--tags", "xxx=xxx"
```
The cluster got created without any errors, addons deployed and healthy. I even tried again today.

<details>
<summary>Logs</summary>

```
DEBU running 'mapt aws eks create'                
DEBU Creating EKS                                 
DEBU context initialized for mapt8776219e         
DEBU checking stack spotOption-debug-eks          
DEBU managing stack spotOption-debug-eks          
INFO Updating (spotOption-debug-eks):             
INFO                                              
INFO  +  pulumi:pulumi:Stack debug-eks-spotOption-debug-eks creating (0s)  
DEBU Based on prices for instance types [c6gd.large c7gd.large t4g.medium c8gn.large c8g.large c6g.large c7g.large c6gn.large] is az eu-north-1b, current price is 0.02 with a score of 9 
DEBU Spot data: {[c6gd.large c7gd.large t4g.medium c8gn.large c8g.large c6g.large c7g.large c6gn.large] 0.02782 eu-north-1 eu-north-1b 0} 
INFO @ updating.......                            
INFO  +  rh:qe:aws:bso bso-bso creating (0s)      
INFO @ updating.....                              
INFO  +  pulumi:pulumi:Stack debug-eks-spotOption-debug-eks created (5s)  
INFO  +  rh:qe:aws:bso bso-bso created            
INFO Outputs:                                     
INFO     az           : "eu-north-1b"             
INFO     instancetypes: [                         
INFO         [0]: "c6gd.large"                    
INFO         [1]: "c7gd.large"                    
INFO         [2]: "t4g.medium"                    
INFO         [3]: "c8gn.large"                    
INFO         [4]: "c8g.large"                     
INFO         [5]: "c6g.large"                     
INFO         [6]: "c7g.large"                     
INFO         [7]: "c6gn.large"                    
INFO     ]                                        
INFO     max          : 0.02782                   
INFO     region       : "eu-north-1"              
INFO     score        : 0                         
INFO                                              
INFO Resources:                                   
INFO     + 2 created                              
INFO                                              
INFO Duration: 7s                                 
INFO                                              
DEBU Getting availability zones for region region: eu-north-1, excludedZoneIDs: [] 
DEBU Got availability zones: [eu-north-1a eu-north-1b eu-north-1c] 
DEBU managing stack stackCreateEKS-debug-eks      
INFO Updating (stackCreateEKS-debug-eks):         
INFO                                              
INFO  +  pulumi:pulumi:Stack debug-eks-stackCreateEKS-debug-eks creating (0s)  
INFO @ updating......                             
INFO  +  aws:ec2:Vpc vpc-main-aeks-net creating (0s)  
INFO  +  aws:iam:Role nodegroup-iam-role creating (0s)  
INFO  +  aws:iam:Role eks-iam-eksRole creating (0s)  
INFO @ updating....                               
INFO  +  aws:iam:Policy loadBalancerControllerPolicy creating (0s)  
INFO @ updating.....                              
INFO  +  aws:ec2:Vpc vpc-main-aeks-net created (2s)  
INFO  +  aws:iam:Role nodegroup-iam-role created (2s)  
INFO  +  aws:iam:Role eks-iam-eksRole created (2s)  
INFO  +  aws:iam:Policy loadBalancerControllerPolicy created (2s)  
INFO @ updating....                               
INFO  +  aws:ec2:Subnet subnet-publicmain-aeks-net0 creating (0s)  
INFO  +  aws:ec2:Subnet subnet-publicmain-aeks-net2 creating (0s)  
INFO  +  aws:ec2:SecurityGroup default-main-aeks-net-main-aeks-net creating (0s)  
INFO  +  aws:ec2:InternetGateway igw-main-aeks-net creating (0s)  
INFO  +  aws:ec2:Subnet subnet-publicmain-aeks-net1 creating (0s)  
INFO  +  aws:ec2:SecurityGroup main-aeks-sg creating (0s)  
INFO  +  aws:iam:RolePolicyAttachment ngpa-2 creating (0s)  
INFO  +  aws:iam:RolePolicyAttachment ngpa-1 creating (0s)  
INFO  +  aws:iam:InstanceProfile eks-node-instance-profile creating (0s)  
INFO  +  aws:iam:RolePolicyAttachment ngpa-0 creating (0s)  
INFO @ updating....                               
INFO  +  aws:iam:RolePolicyAttachment rpa-0 creating (0s)  
INFO  +  aws:iam:RolePolicyAttachment rpa-1 creating (0s)  
INFO @ updating......                             
INFO  +  aws:ec2:InternetGateway igw-main-aeks-net created (4s)  
INFO @ updating.....                              
INFO  +  aws:iam:RolePolicyAttachment ngpa-2 created (5s)  
INFO @ updating....                               
INFO  +  aws:ec2:SecurityGroup default-main-aeks-net-main-aeks-net created (6s)  
INFO  +  aws:iam:RolePolicyAttachment ngpa-1 created (6s)  
INFO @ updating....                               
INFO  +  aws:iam:RolePolicyAttachment ngpa-0 created (7s)  
INFO  +  aws:ec2:SecurityGroup main-aeks-sg created (8s)  
INFO @ updating....                               
INFO  +  aws:iam:RolePolicyAttachment rpa-0 created (8s)  
INFO @ updating....                               
INFO  +  aws:iam:RolePolicyAttachment rpa-1 created (9s)  
INFO  +  aws:ec2:RouteTable routeTable-publicmain-aeks-net1 creating (0s)  
INFO  +  aws:ec2:RouteTable routeTable-publicmain-aeks-net0 creating (0s)  
INFO  +  aws:ec2:RouteTable routeTable-publicmain-aeks-net2 creating (0s)  
INFO @ updating......                             
INFO  +  aws:ec2:Subnet subnet-publicmain-aeks-net0 created (13s)  
INFO  +  aws:iam:InstanceProfile eks-node-instance-profile created (13s)  
INFO @ updating....                               
INFO  +  aws:ec2:Subnet subnet-publicmain-aeks-net2 created (14s)  
INFO @ updating.....                              
INFO  +  aws:ec2:Subnet subnet-publicmain-aeks-net1 created (15s)  
INFO  +  aws:ec2:RouteTable routeTable-publicmain-aeks-net1 created (5s)  
INFO @ updating....                               
INFO  +  aws:ec2:RouteTable routeTable-publicmain-aeks-net0 created (6s)  
INFO @ updating....                               
INFO  +  aws:ec2:RouteTable routeTable-publicmain-aeks-net2 created (7s)  
INFO @ updating....                               
INFO  +  aws:eks:Cluster eks-cluster creating (0s)  
INFO @ updating....                               
INFO  +  aws:ec2:RouteTableAssociation routeTableAssociation-publicmain-aeks-net1 creating (0s)  
INFO  +  aws:ec2:RouteTableAssociation routeTableAssociation-publicmain-aeks-net0 creating (0s)  
INFO @ updating....                               
INFO  +  aws:ec2:RouteTableAssociation routeTableAssociation-publicmain-aeks-net2 creating (0s)  
INFO @ updating.....                              
INFO  +  aws:ec2:RouteTableAssociation routeTableAssociation-publicmain-aeks-net1 created (2s)  
INFO @ updating....                               
INFO  +  aws:ec2:RouteTableAssociation routeTableAssociation-publicmain-aeks-net0 created (3s)  
INFO @ updating....                               
INFO  +  aws:ec2:RouteTableAssociation routeTableAssociation-publicmain-aeks-net2 created (3s)  
INFO @ updating......................................................................................................................................................................................................................................................................................................................................................................................................................................... 
INFO  +  aws:eks:Cluster eks-cluster created (427s)  
INFO @ updating.....                              
INFO  +  aws:ec2:LaunchTemplate main-aeks-lt creating (0s)  
INFO  +  aws:iam:Role AmazonEKS_EBS_CSI_DriverRole creating (0s)  
INFO  +  aws:iam:OpenIdConnectProvider my-oidc-provider creating (0s)  
INFO  +  aws:iam:Role loadBalancerControllerRole creating (0s)  
INFO  +  aws:eks:AccessEntry node-access creating (0s)  
INFO  +  pulumi:providers:kubernetes k8sProvider creating (0s)  
INFO @ updating......                             
INFO  +  aws:iam:Role AmazonEKS_EBS_CSI_DriverRole created (3s)  
INFO  +  aws:iam:OpenIdConnectProvider my-oidc-provider created (3s)  
INFO @ updating.....                              
INFO  +  aws:iam:Role loadBalancerControllerRole created (5s)  
INFO @ updating....                               
INFO  +  aws:eks:AccessEntry node-access created (6s)  
INFO  +  pulumi:providers:kubernetes k8sProvider created (5s)  
INFO @ updating....                               
INFO  +  aws:ec2:LaunchTemplate main-aeks-lt created (7s)  
INFO @ updating....                               
INFO  +  aws:iam:RolePolicyAttachment AmazonEBSCSIDriverPolicyAttachment creating (0s)  
INFO @ updating....                               
INFO  +  aws:iam:RolePolicyAttachment loadBalancerControllerPolicyAttachment creating (0s)  
INFO @ updating......                             
INFO  +  kubernetes:core/v1:ServiceAccount lbcK8sServiceAccount creating (0s)  
INFO  +  aws:autoscaling:Group main-aeks-asg creating (0s)  
INFO @ updating....                               
INFO  +  aws:iam:RolePolicyAttachment AmazonEBSCSIDriverPolicyAttachment created (5s)  
INFO @ updating....                               
INFO  +  aws:iam:RolePolicyAttachment loadBalancerControllerPolicyAttachment created (4s)  
INFO @ updating....                               
2
INFO  +  kubernetes:core/v1:ServiceAccount lbcK8sServiceAccount creating (3s)  
INFO  +  kubernetes:core/v1:ServiceAccount lbcK8sServiceAccount created (3s)  
INFO @ updating....................               
INFO  +  aws:autoscaling:Group main-aeks-asg created (19s)  
INFO @ updating....                               
INFO  +  aws:eks:Addon kube-proxy creating (0s)   
INFO  +  aws:eks:Addon vpc-cni creating (0s)      
INFO  +  aws:eks:Addon eks-pod-identity-agent creating (0s)  
INFO @ updating.............................      
INFO  +  aws:eks:Addon kube-proxy created (26s)   
INFO @ updating.....                              
INFO  +  aws:eks:Addon eks-pod-identity-agent created (27s)  
INFO @ updating............                       
INFO  +  aws:eks:Addon vpc-cni created (37s)      
INFO @ updating....                               
INFO  +  aws:eks:Addon coredns creating (0s)      
INFO @ updating...................                
INFO  +  aws:eks:Addon coredns created (15s)      
INFO @ updating....                               
INFO  +  kubernetes:helm.sh/v3:Chart aws-load-balancer-controller creating (0s)  
INFO  +  aws:eks:Addon aws-ebs-csi-driver creating (0s)  
INFO @ updating......                             
INFO  +  kubernetes:elbv2.k8s.aws/v1beta1:IngressClassParams alb creating (0s)  
INFO  +  kubernetes:core/v1:Service kube-system/aws-load-balancer-webhook-service creating (0s)  
INFO  +  kubernetes:rbac.authorization.k8s.io/v1:RoleBinding kube-system/aws-load-balancer-controller-leader-election-rolebinding creating (0s)  
INFO  +  kubernetes:networking.k8s.io/v1:IngressClass alb creating (0s)  
INFO  +  kubernetes:apps/v1:Deployment kube-system/aws-load-balancer-controller creating (0s)  
INFO  +  kubernetes:rbac.authorization.k8s.io/v1:Role kube-system/aws-load-balancer-controller-leader-election-role creating (0s)  
INFO  +  kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration aws-load-balancer-webhook creating (0s)  
INFO  +  kubernetes:core/v1:Secret kube-system/aws-load-balancer-tls creating (0s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition globalaccelerators.aga.k8s.aws creating (0s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition targetgroupbindings.elbv2.k8s.aws creating (0s)  
INFO  +  kubernetes:rbac.authorization.k8s.io/v1:ClusterRole aws-load-balancer-controller-role creating (0s)  
INFO  +  kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding aws-load-balancer-controller-rolebinding creating (0s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition targetgroupconfigurations.gateway.k8s.aws creating (0s)  
INFO  +  kubernetes:admissionregistration.k8s.io/v1:MutatingWebhookConfiguration aws-load-balancer-webhook creating (0s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition albtargetcontrolconfigs.elbv2.k8s.aws creating (0s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition loadbalancerconfigurations.gateway.k8s.aws creating (0s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition listenerruleconfigurations.gateway.k8s.aws creating (0s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition ingressclassparams.elbv2.k8s.aws creating (0s)  
INFO @ updating....                               
INFO  +  kubernetes:elbv2.k8s.aws/v1beta1:IngressClassParams alb creating (0s) Retry #0; creation failed: no matches for kind "IngressClassParams" in version "elbv2.k8s.aws/v1beta1" 
INFO @ updating....                               
INFO  +  kubernetes:core/v1:Service kube-system/aws-load-balancer-webhook-service creating (1s)  
INFO  +  kubernetes:core/v1:Service kube-system/aws-load-balancer-webhook-service creating (1s) [1/3] Finding Pods to direct traffic to 
INFO  +  kubernetes:elbv2.k8s.aws/v1beta1:IngressClassParams alb creating (2s) Retry #1; creation failed: no matches for kind "IngressClassParams" in version "elbv2.k8s.aws/v1beta1" 
INFO @ updating....                               
2
INFO  +  kubernetes:rbac.authorization.k8s.io/v1:RoleBinding kube-system/aws-load-balancer-controller-leader-election-rolebinding creating (2s)  
INFO  +  kubernetes:rbac.authorization.k8s.io/v1:RoleBinding kube-system/aws-load-balancer-controller-leader-election-rolebinding created (2s)  
INFO @ updating....                               
2
INFO  +  kubernetes:networking.k8s.io/v1:IngressClass alb creating (3s)  
INFO  +  kubernetes:networking.k8s.io/v1:IngressClass alb created (3s)  
INFO  +  kubernetes:elbv2.k8s.aws/v1beta1:IngressClassParams alb creating (4s) Retry #2; creation failed: no matches for kind "IngressClassParams" in version "elbv2.k8s.aws/v1beta1" 
INFO @ updating....                               
INFO  +  kubernetes:apps/v1:Deployment kube-system/aws-load-balancer-controller creating (4s)  
INFO  +  kubernetes:apps/v1:Deployment kube-system/aws-load-balancer-controller creating (5s) warning: [MinimumReplicasUnavailable] Deployment does not have minimum availability. 
INFO  +  kubernetes:apps/v1:Deployment kube-system/aws-load-balancer-controller creating (5s) Waiting for app ReplicaSet to be available (0/2 Pods available) 
INFO @ updating....                               
2
INFO  +  kubernetes:rbac.authorization.k8s.io/v1:Role kube-system/aws-load-balancer-controller-leader-election-role creating (5s)  
INFO  +  kubernetes:rbac.authorization.k8s.io/v1:Role kube-system/aws-load-balancer-controller-leader-election-role created (5s)  
INFO @ updating....                               
2
INFO  +  kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration aws-load-balancer-webhook creating (6s)  
INFO  +  kubernetes:admissionregistration.k8s.io/v1:ValidatingWebhookConfiguration aws-load-balancer-webhook created (6s)  
INFO @ updating....                               
2
INFO  +  kubernetes:core/v1:Secret kube-system/aws-load-balancer-tls creating (7s)  
INFO  +  kubernetes:core/v1:Secret kube-system/aws-load-balancer-tls created (7s)  
INFO  +  kubernetes:elbv2.k8s.aws/v1beta1:IngressClassParams alb creating (8s) Retry #3; creation failed: no matches for kind "IngressClassParams" in version "elbv2.k8s.aws/v1beta1" 
INFO @ updating....                               
2
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition globalaccelerators.aga.k8s.aws creating (8s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition globalaccelerators.aga.k8s.aws created (8s)  
INFO @ updating.....                              
2
INFO  +  kubernetes:rbac.authorization.k8s.io/v1:ClusterRole aws-load-balancer-controller-role creating (10s)  
INFO  +  kubernetes:rbac.authorization.k8s.io/v1:ClusterRole aws-load-balancer-controller-role created (10s)  
2
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition targetgroupbindings.elbv2.k8s.aws creating (10s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition targetgroupbindings.elbv2.k8s.aws created (10s)  
INFO @ updating....                               
INFO  +  kubernetes:core/v1:Service kube-system/aws-load-balancer-webhook-service creating (11s) Service initialization complete 
INFO  +  kubernetes:core/v1:Service kube-system/aws-load-balancer-webhook-service creating (11s)  
INFO  +  kubernetes:core/v1:Service kube-system/aws-load-balancer-webhook-service created (11s)  
INFO @ updating....                               
2
INFO  +  kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding aws-load-balancer-controller-rolebinding creating (12s)  
INFO  +  kubernetes:rbac.authorization.k8s.io/v1:ClusterRoleBinding aws-load-balancer-controller-rolebinding created (12s)  
2
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition targetgroupconfigurations.gateway.k8s.aws creating (12s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition targetgroupconfigurations.gateway.k8s.aws created (12s)  
INFO @ updating.....                              
INFO  +  kubernetes:apps/v1:Deployment kube-system/aws-load-balancer-controller creating (15s) warning: [Pod kube-system/aws-load-balancer-controller-664d68f86d-68f2z]: containers with unready status: [aws-load-balancer-controller] 
INFO  +  kubernetes:apps/v1:Deployment kube-system/aws-load-balancer-controller creating (15s) warning: [Pod kube-system/aws-load-balancer-controller-664d68f86d-65pgr]: containers with unready status: [aws-load-balancer-controller] 
INFO @ updating....                               
2
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition albtargetcontrolconfigs.elbv2.k8s.aws creating (15s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition albtargetcontrolconfigs.elbv2.k8s.aws created (15s)  
2
INFO  +  kubernetes:admissionregistration.k8s.io/v1:MutatingWebhookConfiguration aws-load-balancer-webhook creating (15s)  
INFO  +  kubernetes:admissionregistration.k8s.io/v1:MutatingWebhookConfiguration aws-load-balancer-webhook created (15s)  
INFO  +  kubernetes:elbv2.k8s.aws/v1beta1:IngressClassParams alb creating (16s) Retry #4; creation failed: no matches for kind "IngressClassParams" in version "elbv2.k8s.aws/v1beta1" 
INFO @ updating.....                              
2
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition loadbalancerconfigurations.gateway.k8s.aws creating (17s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition loadbalancerconfigurations.gateway.k8s.aws created (17s)  
INFO @ updating....                               
2
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition listenerruleconfigurations.gateway.k8s.aws creating (19s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition listenerruleconfigurations.gateway.k8s.aws created (19s)  
INFO @ updating.....                              
2
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition ingressclassparams.elbv2.k8s.aws creating (20s)  
INFO  +  kubernetes:apiextensions.k8s.io/v1:CustomResourceDefinition ingressclassparams.elbv2.k8s.aws created (20s)  
INFO @ updating......                             
INFO  +  kubernetes:apps/v1:Deployment kube-system/aws-load-balancer-controller creating (24s) Waiting for app ReplicaSet to be available (1/2 Pods available) 
INFO @ updating....                               
INFO  +  kubernetes:apps/v1:Deployment kube-system/aws-load-balancer-controller creating (24s) Deployment initialization complete 
INFO  +  kubernetes:apps/v1:Deployment kube-system/aws-load-balancer-controller creating (24s)  
INFO  +  kubernetes:apps/v1:Deployment kube-system/aws-load-balancer-controller created (24s)  
INFO @ updating...........                        
2
INFO  +  kubernetes:elbv2.k8s.aws/v1beta1:IngressClassParams alb creating (32s)  
INFO  +  kubernetes:elbv2.k8s.aws/v1beta1:IngressClassParams alb created (32s)  
INFO @ updating...............                    
INFO  +  aws:eks:Addon aws-ebs-csi-driver created (48s)  
INFO @ updating..............                     
INFO  +  pulumi:pulumi:Stack debug-eks-stackCreateEKS-debug-eks created (602s)  
INFO Outputs:                                     
REDACTED
```
</details>

**Comment by adrianriobo** [comment]
@anjannath ahah I thought the error was reported by @zdrapela, so my question is for you, did you have compute-size set when you were getting that error?

**Review by adrianriobo — APPROVED** [review]
LGTM
